# Generated by Django 4.1.5 on 2023-01-05 18:13

from django.db import migrations
import requests


def load_countries(apps, schema_editor):
    resp = requests.get('https://countriesnow.space/api/v0.1/countries/capital')
    resp.raise_for_status()
    country_list = resp.json()['data']
    
    Quiz = apps.get_model('quiz', 'Quiz')
    
    for country in country_list:
        c = Quiz(country=country['name'], capital=country['capital'])
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_delete_guess'),
    ]

    operations = [
        migrations.RunPython(load_countries)
    ]
